language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IA7o43w0Jq6agRkOfro/x80Nyubeccjx85mPNA5tPDW2QwVrkFdhw0E4bc74hjs3pp+e36DrPMiU+tY8nGLidT5mFJmizMqQDT5SdWFVH6heFMn5FTXBU1t4g2qdJDdvq9rn7Fmv16FwesuGFrU9VVUPgfK40qyDPNTV3C3n0khClzOTLblbClRXffLxX2LJYjY7GG//5BuHkrtqOfgVW8CV6cDhZkpXywlsVM03btz8s4YnOVBYGQiDcxBrignCbYFCBp0PSrAX8unBisnTRjNCiZZwa9yWaMpRUqXdcDQ/eSk2I98/Jin2GYlY/1NSY0Bu9y0G5pF09KvY0Syyz04fKgB2HQdX7x+GUaj9ySXibDMft9KHFrpmTr/qQPEDBykykpHrA0cEhkVxZlSbCIoewAWxPIKlQtAwUmFezGumVDkZEdI2JTrfNOVEO+bngbfVSEG5mhWmQ/eNMmRt/lxrzJXqQStlYpmfvgRqrosZiQZStq/Uw4KI3GxK71Y+zxzgCRvwiYprFfush3dyHtx6XMkYNDY+bEp2w0Q6oJzNMPM6nAgxlhC60f0EZMqW1oBbSZ1KBlDQrlRBvNWyhomFzVXnD1gfadqSH8IivlFVeoY3WdgB6YCfrc+HVrqwkE7Lhen+J2VvCpqQW//Dv284TOkhQbOd5owtU4TXj/Y=
  file:
    - "remark-reference-links.js"
    - "remark-reference-links.min.js"
  on:
    tags: true
