language: node_js
node_js:
- '4.0'
- '7.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: TdUcH2jpPA2uTwdqQV2Jx03dY/9M0LrqPlKbO3ZfbI5aZhkvw7kbj1gMu747p2TodojNLBZpc2SGb4fMPCXCq/CcT+KrKKocfEsNgFMhtNQ6lUmlDN3lT7v1XjmTUebn5OvU4l+8XSFZANOaqrJZYxaTf1aqxQKixywBbpXeJEUPSwf7b8khdwcwzhMNZG36uLbjM9bhB52513ZybRanCD6rltkV1PNf1gxf7UzPKsOmkvk1lZCfFyBhhn7PyLg9tty83UfQkmQDwmuzzQhE+qdBNhhQNwWdqvEYnfJMOodEwTXXNl/RchFEe9BsQv8wocH/VbipKiM41R9TZbSgigTkFrhTHR8METDh9TxbK0jBDlBEMNzK2m/uPa50bXcUm3hwrbibgHe1Se3eMnVHDZ1g2UfDDescDvO4dTwkX3tBd4W3/91gPV9FBqPlTBo1PmgwVYQnG0MsN9UeIyR/KAgiN/XXITywq9kc/Y1SF1f+Z9uXvde/Ujuc5G4m55Fk7Acxbaku9/fArGSwL22WRc3lP8Kja4rvItXLxhHkfwWhJAK332NXXXxtShcHZLGeXKNpybk+elEMZOu2avh4rrzmr/OW/E5nFFs8ki6bUyZrlQFGKGffwEYetbSRNwwDcNRVs+yjY9NyrCrCvWmaN4CFKUQg+zEk1+mUQw8E5l4=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: V5hL0Z+77vBfBPtUdIBiM73cRYZLXRc6WYQzrzqVzGbk7eQnv5idArueQtm8rFTakciq4bewsS4q8R660aHKMN+t2SSgMat8GTfLkzP6I65QWjxRmBuAcU9L9/Jg6zCnfh4TKpiwLAxNcs3Lv8tZln13a/3jZOu1L9r22Hpvx74grCnTpyYeBUxFa2xu2cyizW4nMQakKE3P0LaUkMz1Tv6udNrHEio/d3IyzuNvdbPenUp/isKNAPQFLdD+98on2ss2+4aOYGRCSnkOjy7jeZrj08K9NI6E85W0JJdYif3Hn0/dBlUPL0mH+TjFRVsWM2Kq3DaCtiumQtD+h33gPQyvgEiFZZVGKi8eJrhN2gSsCVY/+ZYQfMXQoXIcP6OUMXxwLXj2UM863hwcsyRKmlIIox5UxDKZc9oaHi10LedNuWirXr0rcTqpMws8nqzr7LRDbyxm/U7aU6hJuuXkl+6I5xxKitjwzt6jdD0z2C20jZSCSeK6Qmi5ZXRiVZ2OuA9S97wZd2+panyleqyerP754a1i4/aKgpehzVH1WJfcONcCQ7H2zvrTQtJ64g/gvzitMHKEVkYe5TypJbqPXWFnfHxxk71s4TxwCjfVCuLygsz7Rj3BazPo6oFCmWUFnLIlQT7hi+N9j9Bsz/MnbiothXJgqOHpHK0A877ZRBg=
    file:
      - "remark-reference-links.js"
      - "remark-reference-links.min.js"
    on:
      tags: true
      node: '7.0'
